---
all:
  vars: 
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: admin
    ansible_ssh_pass: admin
  children:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                SPINE-1:
                SPINE-2:
            DC1_LEAFS:
              hosts:
                LEAF-1:
                LEAF-2:
                LEAF-3:
                LEAF-4:
            DC1_CLIENTS:
              hosts:
                CLIENT-1:
                CLIENT-2:
LEAFS:
  hosts:
    LEAF-1:
    LEAF-2:
CVP:
  hosts:
    cvp.apius.lan:
      ansible_user: cvpadmin
      ansible_password: Apiuslab.123!  
SINGLE:
  hosts:
    CLIENT-1:
      ansible_user: marek
      ansible_ssh_pass: 12apius3

