---
  - hosts: LEAF-1, LEAF-2
    gather_facts: no
    tasks:
    - name: Add VLANs
      eos_vlans:
        config:
        - vlan_id: "{{ item.id }}"
          name: "{{ item.name }}"
        state: merged
      with_items: 
        - "{{ vlans }}"

