---
- name: Add VLANs on Arista Switch
  hosts: DC1_CLIENTS  # or any other appropriate group that includes CLIENT-1
  gather_facts: no

  tasks:
    - name: Configure VLANs
      arista.eos.eos_config:
        lines:
          - vlan {{ item.id }}
          - name {{ item.name }}
      loop: "{{ vlans }}"