---
- name: Set MOTD on Arista Switch
  hosts: SWITCH-1
  gather_facts: no
  tasks:
  - name: Update MOTD
    arista.eos.eos_banner:
      banner: login
      text: "{{ motd_banner }}"
      state: present
